import type { Vec } from '../geometry.js';
import { PHI } from '../geometry.js';
import type { Tile, TilingDefinition } from './types.js';

/**
 * The Jeandel–Rao aperiodic set of 11 Wang tiles.
 *
 * A Wang tile is a unit square with a colour on each of its four edges; tiles
 * may only be translated, and two neighbours must agree on the colour of the
 * edge they share. Jeandel and Rao, *An aperiodic set of 11 Wang tiles*,
 * Advances in Combinatorics 2021:1 (arXiv:1506.06492), settled the question
 * Wang raised in 1961: their set tiles the plane, no tiling of it is periodic,
 * and by an exhaustive search no aperiodic Wang set has fewer than 11 tiles,
 * nor fewer than 4 colours.
 *
 * Two presentations of the same 11 tiles appear below, both written as
 * (east, north, west, south) — the paper's (t_w, t_e, t_s, t_n) reordered so
 * that the horizontal pair comes first.
 *
 *   * `JEANDEL_RAO_T` is the set T of the paper's Figure 3: horizontal colours
 *     {0,1,2,3} on west/east and vertical colours {0,1,2,3,4} on south/north.
 *   * `JEANDEL_RAO_T_PRIME` is the minimal set T' of the paper's Figure 4,
 *     "obtained from T by collapsing the colors 4 and 0". That leaves the
 *     single alphabet {0,1,2,3}, and it is this four-colour set that realises
 *     the minimality half of the theorem. Collapsing two colours only ever adds
 *     legal adjacencies, so every T-tiling is also a T'-tiling; Jeandel and Rao
 *     prove T' aperiodic in its own right (their Theorem 3).
 *
 * The rendering colours the four triangles of each square by the four edge
 * colours of T', so the picture shows the matching rule directly: neighbours
 * agree exactly when the two triangles across a grid line have the same
 * colour and merge into a diamond.
 *
 * ## Where the patches come from
 *
 * Enumerating legal patches by backtracking would be both slow and prone to
 * settling into a periodic-looking corner of the shift. Instead patches are
 * read off the exact toral coding of Labbé, *A Markov partition for
 * Jeandel–Rao aperiodic Wang tilings*, Annales Henri Lebesgue 4 (2021) 283–324
 * (arXiv:1903.06137), also described in his *Substitutive structure of
 * Jeandel–Rao aperiodic tilings*, Advances in Applied Mathematics 170 (2025)
 * 102912 (arXiv:1808.07768).
 *
 * Let Γ₀ be the lattice generated by (φ, 0) and (1, φ+3), so that the torus
 * 𝕋₀ = ℝ²/Γ₀ has the rectangle [0, φ) × [0, φ+3) as a fundamental domain, and
 * let 𝒫₀ be the partition of 𝕋₀ into the 24 convex polygons of `ATOMS` below,
 * labelled by the 11 tiles. Labbé proves that 𝒫₀ is a Markov partition for the
 * ℤ²-action generated by the two unit translations, and that coding the orbit
 * of a point,
 *
 *     tiling(a, b) = the atom of 𝒫₀ containing (x₀ + a, y₀ + b) mod Γ₀,
 *
 * yields a valid Jeandel–Rao tiling for every starting point (x₀, y₀). Both φ
 * and φ+3 are irrational, so the orbit is dense and equidistributed and the
 * coding cannot be periodic. The relative areas of the atoms are therefore the
 * tile frequencies: tile 2 is rarest at (9φ − 14)/22 ≈ 2.55%, tile 7 commonest
 * at (13 − 6φ)/22 ≈ 15.0%.
 *
 * ## The full shift versus its minimal core
 *
 * The coding does not reach every Jeandel–Rao tiling. Labbé (arXiv:1808.07768)
 * shows that the tilings that can be desubstituted indefinitely form a minimal
 * proper subshift Ω_U ⊊ Ω₀ of the full Jeandel–Rao shift, generated by an
 * eventually periodic sequence of 2-dimensional substitutions, and that Ω_U is
 * exactly the closure of the codings above. The remainder of Ω₀ is reached
 * through a horizontal fault line: a configuration containing a biinfinite row
 * of tile 0 can be cut along that row and its lower half slid sideways, and the
 * result is still legal but no longer desubstitutable. Those configurations are
 * conjectured to have measure zero. What this file draws is therefore the
 * minimal substitutive core Ω_U, not an arbitrary member of Ω₀ — which is the
 * right choice for a picture, since Ω_U is the part with the repetitive,
 * hierarchical structure.
 *
 * The partition data is the mathematical content of Labbé's papers, cited
 * above; no code from his GPL-licensed `slabbe` package is reused here.
 */

/** Height of the fundamental domain; its width is φ. */
export const JR_TORUS_HEIGHT = PHI + 3;

/**
 * The 11 tiles of the set T (Jeandel & Rao, Figure 3), as
 * `[east, north, west, south]`.
 */
export const JEANDEL_RAO_T: readonly (readonly [number, number, number, number])[] = [
  [2, 4, 2, 1],
  [2, 2, 2, 0],
  [1, 1, 3, 1],
  [1, 2, 3, 2],
  [3, 1, 3, 3],
  [0, 1, 3, 1],
  [0, 0, 0, 1],
  [3, 1, 0, 2],
  [0, 2, 1, 2],
  [1, 2, 1, 4],
  [3, 3, 1, 2],
];

/** Collapsing the vertical colours 4 and 0 turns T into the four-colour set T'. */
function collapse(colour: number): number {
  return colour === 4 ? 0 : colour;
}

/** The minimal four-colour set T' (Jeandel & Rao, Figure 4). */
export const JEANDEL_RAO_T_PRIME: readonly (readonly [number, number, number, number])[] =
  JEANDEL_RAO_T.map(
    ([east, north, west, south]) =>
      [east, collapse(north), west, collapse(south)] as [number, number, number, number],
  );

/** The four colours of T'; a tile class of the rendering is one of them. */
export const JR_COLOURS = 4;

/**
 * Vertices of the partition, on the grid of five x-coordinates and six
 * y-coordinates of Labbé's construction. `row(y)` is the paper's row of five
 * points at height `y`.
 */
const XS: readonly number[] = [0, PHI ** -2, PHI ** -1, 1, PHI];
const row = (y: number): readonly Vec[] => XS.map((x) => ({ x, y }));

const A = row(0);
const B = row(1);
const C = row(2);
const D = row(PHI + 1);
const E = row(PHI + 2);
const F = row(PHI + 3);

/**
 * The 24 atoms of 𝒫₀ with the tile they code for. Each atom is given by its
 * vertex set; `convexHull` puts them in order, so the listing matches the
 * paper's without imposing a winding on it.
 */
const ATOM_DATA: readonly (readonly [number, readonly Vec[]])[] = [
  [0, [A[0]!, A[2]!, B[2]!]],
  [0, [A[2]!, A[3]!, B[3]!]],
  [0, [A[3]!, A[4]!, B[4]!]],
  [1, [A[0]!, B[0]!, B[2]!]],
  [1, [A[2]!, B[2]!, B[3]!]],
  [1, [A[3]!, B[3]!, B[4]!]],
  [2, [C[0]!, D[0]!, E[2]!]],
  [3, [B[3]!, C[3]!, E[4]!, C[4]!]],
  [4, [C[0]!, E[2]!, E[3]!]],
  [4, [E[2]!, E[3]!, F[3]!]],
  [5, [D[0]!, E[0]!, E[2]!]],
  [5, [E[0]!, E[1]!, F[1]!]],
  [5, [E[1]!, E[2]!, F[3]!]],
  [6, [E[0]!, F[0]!, F[1]!]],
  [6, [E[1]!, F[1]!, F[3]!]],
  [6, [E[3]!, F[3]!, F[4]!]],
  [7, [D[3]!, E[3]!, E[4]!]],
  [7, [E[3]!, E[4]!, F[4]!]],
  [7, [B[0]!, C[0]!, E[3]!]],
  [8, [B[2]!, C[2]!, E[4]!]],
  [9, [B[0]!, B[2]!, C[2]!]],
  [9, [B[2]!, B[3]!, C[3]!]],
  [9, [B[3]!, B[4]!, C[4]!]],
  [10, [B[0]!, D[3]!, E[3]!]],
];

/** Anticlockwise convex hull by the monotone chain algorithm. */
export function convexHull(points: readonly Vec[]): Vec[] {
  const sorted = [...points].sort((p, q) => p.x - q.x || p.y - q.y);
  const half = (pts: readonly Vec[]): Vec[] => {
    const out: Vec[] = [];
    for (const p of pts) {
      while (out.length >= 2) {
        const a = out[out.length - 2]!;
        const b = out[out.length - 1]!;
        if ((b.x - a.x) * (p.y - a.y) - (b.y - a.y) * (p.x - a.x) <= 0) out.pop();
        else break;
      }
      out.push(p);
    }
    return out;
  };
  const lower = half(sorted);
  const upper = half([...sorted].reverse());
  return [...lower.slice(0, -1), ...upper.slice(0, -1)];
}

export interface Atom {
  readonly tile: number;
  readonly polygon: readonly Vec[];
}

export const ATOMS: readonly Atom[] = ATOM_DATA.map(([tile, vertices]) => ({
  tile,
  polygon: convexHull(vertices),
}));

/** Whether `(x, y)` lies in the closed anticlockwise convex polygon. */
function inClosedPolygon(polygon: readonly Vec[], x: number, y: number): boolean {
  for (let i = 0; i < polygon.length; i++) {
    const a = polygon[i]!;
    const b = polygon[(i + 1) % polygon.length]!;
    if ((b.x - a.x) * (y - a.y) - (b.y - a.y) * (x - a.x) < -1e-12) return false;
  }
  return true;
}

/**
 * The point of the fundamental domain representing `(x, y)` modulo Γ₀. Reducing
 * the height first is what makes the second generator (1, φ+3) act: the lattice
 * is sheared, so every whole height stepped down also steps one unit left.
 */
export function toTorus(x: number, y: number): Vec {
  const steps = Math.floor(y / JR_TORUS_HEIGHT);
  const wrapped = ((x - steps) % PHI + PHI) % PHI;
  return { x: wrapped, y: y - steps * JR_TORUS_HEIGHT };
}

/** Which of the 11 tiles the point of the torus codes for. */
export function torusToTile(x: number, y: number): number {
  for (const atom of ATOMS) {
    if (inClosedPolygon(atom.polygon, x, y)) return atom.tile;
  }
  // Unreachable: the atoms cover the closed fundamental domain.
  throw new Error(`point (${x}, ${y}) is outside the partition`);
}

/**
 * A starting point in general position: it keeps the codings of the cells this
 * app draws well clear of the atom boundaries, where a tie would be decided by
 * rounding rather than by the partition.
 */
export const JR_START: Vec = { x: PHI / 3, y: JR_TORUS_HEIGHT / 7 };

/** The tile index at cell `(a, b)` of the tiling coded by `start`. */
export function jeandelRaoTileAt(a: number, b: number, start: Vec = JR_START): number {
  const p = toTorus(start.x + a, start.y + b);
  return torusToTile(p.x, p.y);
}

/**
 * The four triangles of the unit square at `(a, b)`, each carrying the T'
 * colour of the edge it leans on. Neighbouring squares agree on an edge exactly
 * when the two triangles meeting there share a colour.
 */
export function wangTileTriangles(a: number, b: number, tile: number): Tile[] {
  const [east, north, west, south] = JEANDEL_RAO_T_PRIME[tile]!;
  const sw = { x: a, y: b };
  const se = { x: a + 1, y: b };
  const ne = { x: a + 1, y: b + 1 };
  const nw = { x: a, y: b + 1 };
  const mid = { x: a + 0.5, y: b + 0.5 };
  return [
    { kind: south, points: [sw, se, mid] },
    { kind: east, points: [se, ne, mid] },
    { kind: north, points: [ne, nw, mid] },
    { kind: west, points: [nw, sw, mid] },
  ];
}

export function generateJeandelRao(radius: number): Tile[] {
  const cells = Math.ceil(radius) + 1;
  const tiles: Tile[] = [];
  for (let a = -cells; a <= cells; a++) {
    for (let b = -cells; b <= cells; b++) {
      // Squares whose nearest corner is already outside the disc cannot help.
      const dx = Math.max(0, Math.abs(a + 0.5) - 0.5);
      const dy = Math.max(0, Math.abs(b + 0.5) - 0.5);
      if (Math.hypot(dx, dy) > radius) continue;
      for (const triangle of wangTileTriangles(a, b, jeandelRaoTileAt(a, b))) {
        tiles.push(triangle);
      }
    }
  }
  return tiles;
}

export const jeandelRao: TilingDefinition = {
  id: 'jeandel-rao',
  name: 'Jeandel–Rao 11 Wang tiles',
  family: 'experimental',
  description:
    'The smallest possible aperiodic set of Wang tiles: eleven unit squares with coloured edges that tile the plane by translation only, never periodically. Jeandel and Rao proved by exhaustive search that no aperiodic Wang set has fewer than eleven tiles or fewer than four colours, closing a question open since Wang asked it in 1961. Each square is drawn as four triangles carrying its four edge colours, so a legal join is one where the triangles across a grid line merge into a diamond. Patches are not searched for: they are read off Labbé’s Markov partition of the torus ℝ²/⟨(φ,0),(1,φ+3)⟩ into eleven labelled regions, coding the orbit of a point under the two unit translations — an irrational rotation, so the result cannot be periodic. That coding gives the minimal substitutive subshift Ω_U, the part of the Jeandel–Rao shift with hierarchical structure, rather than the fault-line configurations that make up the rest. Jeandel & Rao, An aperiodic set of 11 Wang tiles, Advances in Combinatorics 2021:1 (arXiv:1506.06492); Labbé, A Markov partition for Jeandel–Rao aperiodic Wang tilings, Annales Henri Lebesgue 4 (2021) 283–324 (arXiv:1903.06137); Labbé, Substitutive structure of Jeandel–Rao aperiodic tilings, Adv. Appl. Math. 170 (2025) 102912 (arXiv:1808.07768).',
  kinds: JR_COLOURS,
  kindLabels: ['edge colour 0', 'edge colour 1', 'edge colour 2', 'edge colour 3'],
  reference: 'https://arxiv.org/abs/1506.06492',
  unitTileArea: 0.25,
  generate(radius): Tile[] {
    return generateJeandelRao(radius);
  },
};
