import type { Vec } from '../geometry.js';
import type { Tile, TilingDefinition } from './types.js';

/**
 * De Bruijn's multigrid method. `n` families of parallel lines, the j-th at
 * angle pi*j/n, are dualised into a rhombic tiling with 2n-fold orientational
 * symmetry: n = 5 gives the Penrose rhombs, n = 4 the Ammann–Beenker tiling,
 * n = 6 a dodecagonal quasicrystal, and so on.
 *
 * Every rhomb has unit edges; its class is `min(k - j, n - (k - j)) - 1`, i.e.
 * how "fat" it is.
 *
 * @see https://en.wikipedia.org/wiki/De_Bruijn%27s_theorem
 */
export function multigrid(n: number, offsets: readonly number[], radius: number): Tile[] {
  const dirs: Vec[] = [];
  for (let j = 0; j < n; j++) {
    const a = (Math.PI * j) / n;
    dirs.push({ x: Math.cos(a), y: Math.sin(a) });
  }

  const tiles: Tile[] = [];
  // The grid intersection p and its dual tiling vertex v satisfy
  // v = (n / 2) p + a bounded rounding term. Searching to the output radius
  // in grid space therefore over-generates quadratically (25x for n = 10).
  const gridLimit = (2 * radius) / n + 4;
  const outputLimit = radius + 2;

  for (let j = 0; j < n; j++) {
    const ej = dirs[j]!;
    const gj = offsets[j] ?? 0;
    for (let k = j + 1; k < n; k++) {
      const ek = dirs[k]!;
      const gk = offsets[k] ?? 0;
      const det = ej.x * ek.y - ej.y * ek.x;
      if (Math.abs(det) < 1e-9) continue;
      const diff = k - j;
      const kind = Math.min(diff, n - diff) - 1;

      const mMin = Math.ceil(-gridLimit - gj);
      const mMax = Math.floor(gridLimit - gj);
      const nMin = Math.ceil(-gridLimit - gk);
      const nMax = Math.floor(gridLimit - gk);

      for (let m = mMin; m <= mMax; m++) {
        const cj = m - gj;
        for (let q = nMin; q <= nMax; q++) {
          const ck = q - gk;
          // Solve p . ej = cj, p . ek = ck
          const px = (cj * ek.y - ck * ej.y) / det;
          const py = (ck * ej.x - cj * ek.x) / det;
          if (px * px + py * py > gridLimit * gridLimit) continue;

          // Region indices of the intersection point in every other grid.
          const idx: number[] = new Array<number>(n);
          let degenerate = false;
          for (let i = 0; i < n; i++) {
            if (i === j) {
              idx[i] = m;
            } else if (i === k) {
              idx[i] = q;
            } else {
              const t = px * dirs[i]!.x + py * dirs[i]!.y + (offsets[i] ?? 0);
              if (Math.abs(t - Math.round(t)) < 1e-7) degenerate = true;
              idx[i] = Math.ceil(t);
            }
          }
          if (degenerate) continue;

          const vertex = (dj: number, dk: number): Vec => {
            let x = 0;
            let y = 0;
            for (let i = 0; i < n; i++) {
              const c = idx[i]! + (i === j ? dj : i === k ? dk : 0);
              x += c * dirs[i]!.x;
              y += c * dirs[i]!.y;
            }
            return { x, y };
          };

          const points = [vertex(0, 0), vertex(1, 0), vertex(1, 1), vertex(0, 1)];
          if (
            points.every((point) => point.x < -outputLimit) ||
            points.every((point) => point.y < -outputLimit) ||
            points.every((point) => point.x > outputLimit) ||
            points.every((point) => point.y > outputLimit)
          ) {
            continue;
          }
          tiles.push({ kind, points });
        }
      }
    }
  }
  return tiles;
}

/**
 * Irrational offsets, shifted so that they sum to zero — for n = 5 that is
 * exactly de Bruijn's condition for a genuine Penrose rhombus tiling — and
 * chosen so that no three grid lines meet in a point.
 */
function offsetsFor(n: number): number[] {
  const raw: number[] = [];
  for (let i = 0; i < n; i++) raw.push(((i + 1) * Math.SQRT2 * 0.37) % 1);
  const mean = raw.reduce((a, b) => a + b, 0) / n;
  return raw.map((v) => v - mean);
}

function averageRhombArea(n: number): number {
  let sum = 0;
  let count = 0;
  for (let d = 1; d <= Math.floor(n / 2); d++) {
    sum += Math.sin((Math.PI * d) / n);
    count++;
  }
  return sum / count;
}

function makeMultigridTiling(opts: {
  id: string;
  name: string;
  n: number;
  description: string;
  reference: string;
  kindLabels: string[];
  family?: TilingDefinition['family'];
}): TilingDefinition {
  const offsets = offsetsFor(opts.n);
  return {
    id: opts.id,
    name: opts.name,
    family: opts.family ?? 'quasicrystal',
    description: opts.description,
    kinds: Math.floor(opts.n / 2),
    kindLabels: opts.kindLabels,
    reference: opts.reference,
    unitTileArea: averageRhombArea(opts.n),
    generate(radius) {
      return multigrid(opts.n, offsets, radius);
    },
  };
}

export const penrosePentagrid = makeMultigridTiling({
  id: 'penrose-pentagrid',
  name: 'Penrose rhombs — pentagrid',
  family: 'penrose',
  n: 5,
  description:
    'The same thick and thin rhombs as P3, but generated by de Bruijn’s pentagrid: the dual of five families of parallel lines.',
  reference: 'https://en.wikipedia.org/wiki/Penrose_tiling#Deflation_for_P2_and_P3_tilings',
  kindLabels: ['thin rhomb', 'thick rhomb'],
});

export const ammannBeenker = makeMultigridTiling({
  id: 'ammann-beenker',
  name: 'Ammann–Beenker (8-fold)',
  n: 4,
  description:
    'Ammann’s A5 set: a square and a 45° rhomb with eight-fold orientational symmetry, built from a four-fold multigrid.',
  reference: 'https://en.wikipedia.org/wiki/Ammann%E2%80%93Beenker_tiling',
  kindLabels: ['45° rhomb', 'square'],
});

export const dodecagonal = makeMultigridTiling({
  id: 'dodecagonal',
  name: 'Dodecagonal (12-fold)',
  n: 6,
  description:
    'A twelve-fold quasicrystal of 30°, 60° and 90° rhombs — the rhombic relative of the Socolar and Stampfli tilings.',
  reference: 'https://en.wikipedia.org/wiki/List_of_aperiodic_sets_of_tiles',
  kindLabels: ['30° rhomb', '60° rhomb', 'square'],
});

export const heptagonal = makeMultigridTiling({
  id: 'heptagonal',
  name: 'Heptagonal (14-fold)',
  n: 7,
  description:
    'A seven-fold multigrid quasicrystal with three rhomb shapes — the Danzer-style heptagonal cousin of the Penrose tiling.',
  reference: 'https://en.wikipedia.org/wiki/Quasicrystal',
  kindLabels: ['thin rhomb', 'medium rhomb', 'wide rhomb'],
});

export const decagonal = makeMultigridTiling({
  id: 'decagonal',
  name: 'Decagonal (20-fold)',
  n: 10,
  description:
    'A ten-family multigrid: five rhomb shapes packed into a decagonal quasicrystal.',
  reference: 'https://en.wikipedia.org/wiki/Quasicrystal',
  kindLabels: ['18°', '36°', '54°', '72°', 'square'],
});
